app/urls.py
# -*- coding: utf-8 -*-

from .utils.helpers import HandleError
from .views import (
    addresses, auth, cities, deceased, doctors, graves, main, registries,
    users, zones
)


def init_app(app):
    for blueprint in (
        addresses, auth, cities, deceased, doctors, graves, main, registries,
        users, zones
    ):
        app.register_blueprint(blueprint.bp)

    # errors
    errors = {
        403: u'Acesso Negado!',
        404: u'Página não Encontrada!',
        500: u'Erro Interno do Servidor!'
    }
    for code, message in errors.items():
        app.errorhandler(code)(HandleError('error.html', message))

app/models/user_types.py
# -*- coding: utf-8 -*-

from ..extensions import db
from ..mixins import CRUDMixin


class UserType(CRUDMixin, db.Model):
    __tablename__ = 'user_types'
    description = db.Column(db.String(25), nullable=False)
    role = db.Column(db.String(10), nullable=False)
    users = db.relationship('User', backref='user_type', lazy='dynamic')

    @classmethod
    def populate(cls):
        user_types = [('Administrador', 'admin'), ('Funcionário', 'employee')]
        user_types = [cls(description=d, role=r) for d, r in user_types]
        db.session.bulk_save_objects(user_types)
        db.session.commit()

    def __repr__(self):
        return '{0}({1})'.format(self.__class__.__name__, self.description)

app/models/users.py
# -*- coding: utf-8 -*-

from itertools import chain

from flask import current_app
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from ..extensions import db
from ..mixins import CRUDMixin
from .user_types import UserType


class User(CRUDMixin, UserMixin, db.Model):
    __tablename__ = 'users'
    name = db.Column(db.String(255), nullable=False)
    login = db.Column(db.String(30), nullable=False)
    _pwd_hash = db.Column(db.String(255), nullable=False)
    user_type_id = db.Column(
        db.Integer, db.ForeignKey('user_types.id'), nullable=False
    )

    @classmethod
    def fetch(cls, search, criteria, order, page):
        joins = filters = ()
        columns = cls.__table__.columns.keys()
        orders = ['asc', 'desc']
        items = []

        for k, v in search.items():
            if k in columns and v:
                if k == 'user_type_id':
                    filters += (UserType.description.ilike('%' + v + '%'), )
                    items.append(k)
                else:
                    filters += (getattr(cls, k).ilike('%' + v + '%'), )

        if criteria in columns and order in orders:
            if criteria == 'user_type_id':
                orders = (getattr(UserType.description, order)(), )
                items.append(criteria)
            else:
                orders = (getattr(getattr(cls, criteria), order)(), )

        if 'user_type_id' in items:
            joins += (UserType, )
            filters += (cls.user_type_id == UserType.id, )

        query = cls.query
        if joins:
            query = query.join(*joins)
        if filters:
            query = query.filter(*filters)

        return query.order_by(*orders).paginate(
            page,
            per_page=current_app.config['PER_PAGE'],
            error_out=False
        )

    @staticmethod
    def dump(pagination):
        headers = iter([('NOME', 'LOGIN', 'TIPO')])
        data = (
            (u.name, u.login, u.user_type.description)
            for u in pagination.query.all()
        )
        return chain(headers, data)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self._pwd_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self._pwd_hash, password)

    def is_admin(self):
        return self.user_type.role == 'admin'

    def has_permissions(self, *roles):
        return self.user_type.role in roles

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '{0}({1})'.format(self.__class__.__name__, self.login)

app/forms/users.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import (
    FormField, IntegerField, PasswordField, SelectField, StringField,
    SubmitField
)
from wtforms.validators import InputRequired, Length, DataRequired

from ..models.user_types import UserType
from ..utils.forms import ORDERS, get_fields


class UserForm(FlaskForm):
    login = StringField(
        'Login',
        [InputRequired(message='Insira o login do usuário!'),
         Length(1, 30)]
    )
    name = StringField(
        'Nome',
        [InputRequired(message='Insira o nome do usuário!'),
         Length(1, 255)]
    )
    password = PasswordField(
        'Senha', [InputRequired(message='Insira a senha do usuário!')]
    )
    user_type_id = SelectField(
        'Tipo de Usuário', [
            DataRequired(message='Selecione um tipo de usuário')],
        coerce=int
    )
    submit = SubmitField('Salvar')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.user_type_id.choices = [
            (u.id, u.description) for u in UserType.query.all()
        ]
        self.user_type_id.choices.insert(0, (0, ''))


class UserHeadersForm(FlaskForm):
    login = StringField('Login')
    name = StringField('Nome')
    user_type_id = StringField('Tipo de Usuário')


class UserSearchForm(FlaskForm):
    page = IntegerField('Página', default=1)
    filters = FormField(UserHeadersForm)
    criteria = SelectField(
        'Ordenar por', choices=get_fields(UserHeadersForm), default='name'
    )
    order = SelectField('Ordem', choices=ORDERS, default='asc')

app/views/users.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify, render_template, request, url_for
from flask_login import login_required

from ..decorators import permission_required
from ..extensions import excel
from ..forms.users import UserForm, UserSearchForm
from ..models.users import User

bp = Blueprint('users', __name__, url_prefix='/usuarios')


@bp.route('/')
@login_required
@permission_required('admin')
def index():
    form = UserSearchForm(request.args)
    export = request.args.get('export', 0, type=int)
    filters = form.filters.data
    criteria = form.criteria.data
    order = form.order.data
    pagination = User.fetch(filters, criteria, order, form.page.data)
    users = pagination.items
    filters = {'filters-' + k: v for k, v in filters.items()}

    if export:
        export = User.dump(pagination)
        return excel.make_response_from_array(
            export, 'xlsx', file_name='Usuários.xlsx'
        )

    return render_template(
        'users/index.html',
        icon='fa-users',
        title='Usuários',
        clean_url=url_for('users.index'),
        create_url=url_for('users.create'),
        form=form,
        filters=filters,
        criteria=criteria,
        order=order,
        pagination=pagination,
        users=users
    )


@bp.route('/adicionar', methods=['GET', 'POST'])
@login_required
@permission_required('admin')
def create():
    form = UserForm()

    if form.validate() and request.method == 'POST':
        user = User()
        form.populate_obj(user)
        user.save()
        return jsonify({'redirect': url_for('users.index')})

    return render_template(
        'users/view.html',
        icon='fa-users',
        title='Adicionar Usuário',
        form=form,
        method='post',
        color='success'
    )


@bp.route('/<int:id>', methods=['GET', 'PUT'])
@login_required
@permission_required('admin')
def edit(id):
    view = request.args.get('format', '', type=str)
    title = 'Usuário' if view == 'view' else 'Editar Usuário'

    user = User.get_or_404(id)
    obj = {'obj': user} if request.method == 'GET' else {}
    form = UserForm(**obj)

    if form.validate() and request.method == 'PUT':
        form.populate_obj(user)
        user.update()
        return jsonify({'redirect': url_for('users.index')})

    return render_template(
        'users/view.html',
        icon='fa-users',
        title=title,
        form=form,
        method='put',
        color='warning',
        view=bool(view)
    )


@bp.route('/<int:id>', methods=['DELETE'])
@login_required
@permission_required('admin')
def delete(id):
    User.get_or_404(id).delete()
    return '', 204

app/templates/users/index.html
{% from '_macros.html' import render_pagination, render_modal %}
{% extends '_index.html' %}

{% block results %}
  {% for u in users %}
    <tr>
      <td>{{ u.login }}</td>
      <td>{{ u.name }}</td>
      <td>{{ u.user_type.description }}</td>
      <td>
        <a href="{{ url_for('users.edit', id=u.id, format='view') }}" class="btn btn-raised btn-info" title="Visualizar">
          <i class="fas fa-eye"></i>
        </a>
        {% if current_user.is_admin() %}
          <a href="{{ url_for('users.edit', id=u.id) }}" class="btn btn-raised btn-warning" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a class="btn btn-raised btn-danger" data-delete-href="{{ url_for('users.delete', id=u.id) }}" onclick="app.methods.remove(this)" title="Remover">
            <i class="fas fa-trash"></i>
          </a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

{% block paginator %}
{{ render_pagination(pagination, 'users.index', criteria=criteria, order=order, **filters) }}
{% endblock %}

{% block dialog %}
{% call render_modal('modal-delete', 'Remover Usuario', yes_text='Remover', yes_icon='trash', yes_color='danger') %}
  <p>Deseja realmente remover o Usuario?</p>
{% endcall %}
{% endblock %}

app/templates/users/view.html
{% from '_macros.html' import render_field %}

{% extends "_view.html" %}

{% block editor %}
{{ form.csrf_token }}
{{ render_field(form.login, class_="col-md-6", autofocus=True, required=True) }}
{{ render_field(form.name, class_="col-md-6", required=True) }}
{{ render_field(form.password, class_="col-md-6", required=True) }}
{{ render_field(form.user_type_id, class_="col-md-6", required=True) }}
{% endblock %}

{% block report %}
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th class="col-md-1">{{ form.login.label }}</th>
      <td>{{ form.login.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.name.label }}</th>
      <td>{{ form.name.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.password.label }}</th>
      <td>* * *</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.user_type_id.label }}</th>
      <td>{{ dict(form.user_type_id.choices).get(form.user_type_id.data) }}</td>
    </tr>
  </table>
</div>
{% endblock %}