app/urls.py
# -*- coding: utf-8 -*-

from .utils.helpers import HandleError
from .views import (
    addresses, auth, cities, deceased, doctors, graves, main, registries,
    users, zones
)


def init_app(app):
    for blueprint in (
        addresses, auth, cities, deceased, doctors, graves, main, registries,
        users, zones
    ):
        app.register_blueprint(blueprint.bp)

    # errors
    errors = {
        403: u'Acesso Negado!',
        404: u'Página não Encontrada!',
        500: u'Erro Interno do Servidor!'
    }
    for code, message in errors.items():
        app.errorhandler(code)(HandleError('error.html', message))

app/models/graves.py
# -*- coding: utf-8 -*-

import csv
import os
from itertools import chain
from re import DOTALL, findall

from flask import current_app

from config import basedir

from ..extensions import db
from ..mixins import CRUDMixin
from .zones import Zone


class Grave(CRUDMixin, db.Model):
    __tablename__ = 'graves'
    street = db.Column(db.String(5), nullable=False)
    number = db.Column(db.String(5), nullable=False)
    zone_id = db.Column(db.Integer, db.ForeignKey('zones.id'), nullable=False)
    deceased = db.relationship('Deceased', backref='grave', lazy='dynamic')

    @classmethod
    def fetch(cls, search, criteria, order, page):
        joins = filters = ()
        columns = cls.__table__.columns.keys()
        orders = ['asc', 'desc']
        items = []

        for k, v in search.items():
            if k in columns and v:
                if (k == 'street' and findall(r'^\w+ \w+$', v, flags=DOTALL)):
                    v = v.split()
                    filters += (
                        cls.street.ilike('%' + v[0] + '%'),
                        cls.number.ilike('%' + v[1] + '%'),
                    )
                elif k == 'zone_id':
                    if v.isnumeric():
                        filters += (cls.zone_id == v, )
                    elif findall(r'^\w+ \w+$', v, flags=DOTALL):
                        v = v.split()
                        filters += (
                            Zone.description.ilike('%' + v[0] + '%'),
                            Zone.complement.ilike('%' + v[1] + '%'),
                        )
                    else:
                        filters += (Zone.description.ilike('%' + v + '%'), )
                    items.append(k)
                else:
                    filters += (getattr(cls, k).ilike('%' + v + '%'), )

        if criteria in columns and order in orders:
            if criteria == 'zone_id':
                orders = (getattr(Zone.description, order)(), )
                items.append(criteria)
            else:
                orders = (db.func.length(getattr(cls, criteria)), )
                orders += (getattr(getattr(cls, criteria), order)(), )

        if 'zone_id' in items:
            joins += (Zone, )
            filters += (cls.zone_id == Zone.id, )

        query = cls.query
        if joins:
            query = query.join(*joins)
        if filters:
            query = query.filter(*filters)

        return query.order_by(*orders).paginate(
            page,
            per_page=current_app.config['PER_PAGE'],
            error_out=False
        )

    def serialize(self):
        name = []
        if self.street:
            name.append('Rua ' + self.street)
        if self.number:
            name.append('Túmulo ' + self.number)

        return {'id': self.id, 'name': ' - '.join(name)}

    @classmethod
    def populate(cls):
        zones = {
            z.description + '-' + z.complement: int(z.id)
            for z in Zone.query.all()
        }
        path = os.path.join(basedir, 'seeds', 'graves.tsv')
        with open(path) as f:
            reader = csv.DictReader(f, delimiter='\t')
            graves = [
                cls(
                    street=row['RUA'],
                    number=row['NÚMERO'],
                    zone_id=zones[row['REGIÃO'] + '-' + row['COMPLEMENTO']]
                ) for row in reader
            ]
        db.session.bulk_save_objects(graves)
        db.session.commit()

    @staticmethod
    def dump(pagination):
        headers = iter([('RUA', 'NÚMERO', 'REGIÃO')])
        data = (
            (
                g.street, g.number,
                g.zone.serialize().get('name') if g.zone else ''
            ) for g in pagination.query.all()
        )
        return chain(headers, data)

    def __repr__(self):
        return '{0}({1} {2})'.format(
            self.__class__.__name__, self.street, self.number
        )

app/forms/graves.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import (
    FormField, IntegerField, SelectField, StringField, SubmitField
)
from wtforms.validators import InputRequired, Length

from ..models.zones import Zone
from ..utils.forms import ORDERS, get_fields


class GraveForm(FlaskForm):
    street = StringField(
        'Rua',
        [InputRequired(message='Insira a rua do túmulo!'),
         Length(1, 255)]
    )
    number = StringField(
        'Número',
        [InputRequired(message='Insira o número do túmulo!'),
         Length(1, 255)]
    )
    zone_id = SelectField(
        'Região', [InputRequired(message='Selecione uma região!')],
        choices=(),
        coerce=int
    )
    submit = SubmitField('Salvar')

    def refill(cls):
        if cls.zone_id.data:
            zone = Zone.get_or_404(cls.zone_id.data)
            cls.zone_id.choices = [tuple(zone.serialize().values())]


class GraveHeadersForm(FlaskForm):
    street = StringField('Rua')
    number = StringField('Número')
    zone_id = StringField('Região')


class GraveSearchForm(FlaskForm):
    page = IntegerField('Página', default=1)
    filters = FormField(GraveHeadersForm)
    criteria = SelectField(
        'Ordenar por', choices=get_fields(GraveHeadersForm), default='street'
    )
    order = SelectField('Ordem', choices=ORDERS, default='asc')

app/views/graves.py
# -*- coding: utf-8 -*-

from flask import Blueprint, jsonify, render_template, request, url_for
from flask_login import current_user, login_required

from ..decorators import permission_required
from ..extensions import excel
from ..forms.graves import GraveForm, GraveSearchForm
from ..models.graves import Grave

bp = Blueprint('graves', __name__, url_prefix='/tumulos')


@bp.route('/')
@login_required
def index():
    form = GraveSearchForm(request.args)
    export = request.args.get('export', 0, type=int)
    json = request.args.get('json', 0, type=int)
    filters = form.filters.data
    criteria = form.criteria.data
    order = form.order.data
    pagination = Grave.fetch(filters, criteria, order, form.page.data)
    graves = pagination.items
    filters = {'filters-' + k: v for k, v in filters.items()}

    if export and current_user.is_admin():
        export = Grave.dump(pagination)
        return excel.make_response_from_array(
            export, 'xlsx', file_name='Túmulos.xlsx'
        )

    if json:
        return jsonify({'result': [g.serialize() for g in graves]})

    return render_template(
        'graves/index.html',
        icon='fa-tombstone',
        title='Túmulos',
        clean_url=url_for('graves.index'),
        create_url=url_for('graves.create'),
        form=form,
        filters=filters,
        criteria=criteria,
        order=order,
        pagination=pagination,
        graves=graves
    )


@bp.route('/adicionar', methods=['GET', 'POST'])
@login_required
@permission_required('admin')
def create():
    form = GraveForm()
    form.refill()

    if form.validate() and request.method == 'POST':
        grave = Grave()
        form.populate_obj(grave)
        grave.save()
        return jsonify({'redirect': url_for('graves.index')})

    return render_template(
        'graves/view.html',
        icon='fa-tombstone',
        title='Adicionar Túmulo',
        form=form,
        method='post',
        color='success'
    )


@bp.route('/<int:id>', methods=['GET', 'PUT'])
@login_required
def edit(id):
    view = request.args.get('format', '', type=str)
    title = 'Túmulo' if view == 'view' else 'Editar Túmulo'
    view = True if not current_user.is_admin() else view

    grave = Grave.get_or_404(id)
    obj = {'obj': grave} if request.method == 'GET' else {}
    form = GraveForm(**obj)
    form.refill()

    if form.validate() and current_user.is_admin() and request.method == 'PUT':
        form.populate_obj(grave)
        grave.update()
        return jsonify({'redirect': url_for('graves.index')})

    return render_template(
        'graves/view.html',
        icon='fa-tombstone',
        title=title,
        form=form,
        method='put',
        color='warning',
        view=bool(view)
    )


@bp.route('/<int:id>', methods=['DELETE'])
@login_required
@permission_required('admin')
def delete(id):
    Grave.get_or_404(id).delete()
    return '', 204

app/templates/graves/index.html
{% from '_macros.html' import render_pagination, render_modal %}
{% extends '_index.html' %}

{% block results %}
  {% for g in graves %}
    <tr>
      <td>{{ g.street }}</td>
      <td>{{ g.number }}</td>
      <td>{{ g.zone.description }} {% if g.zone.complement %} - {{ g.zone.complement }}{% endif %}</td>
      <td>
        <a href="{{ url_for('graves.edit', id=g.id, format='view') }}" class="btn btn-raised btn-info" title="Visualizar">
          <i class="fas fa-eye"></i>
        </a>
        {% if current_user.is_admin() %}
          <a href="{{ url_for('graves.edit', id=g.id) }}" class="btn btn-raised btn-warning" title="Editar">
            <i class="fas fa-edit"></i>
          </a>
          <a class="btn btn-raised btn-danger" data-delete-href="{{ url_for('graves.delete', id=g.id) }}" onclick="app.methods.remove(this)" title="Remover">
            <i class="fas fa-trash"></i>
          </a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

{% block paginator %}
{{ render_pagination(pagination, 'graves.index', criteria=criteria, order=order, **filters) }}
{% endblock %}

{% block dialog %}
{% call render_modal('modal-delete', 'Remover Tumulo', yes_text='Remover', yes_icon='trash', yes_color='danger') %}
  <p>Deseja realmente remover o Tumulo?</p>
{% endcall %}
{% endblock %}

app/templates/graves/view.html
{% from '_macros.html' import render_field %}

{% extends "_view.html" %}

{% block editor %}
{{ form.csrf_token }}
{{ render_field(form.street, class_="col-md-6", autofocus=True, required=True) }}
{{ render_field(form.number, class_="col-md-6", required=True) }}
{{ render_field(form.zone_id, class="zone", class_="col-md-6", required=True) }}
{% endblock %}

{% block report %}
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th class="col-md-1">{{ form.street.label }}</th>
      <td>{{ form.street.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.number.label }}</th>
      <td>{{ form.number.data }}</td>
    </tr>
    <tr>
      <th class="col-md-1">{{ form.zone_id.label }}</th>
      <td>{{ dict(form.zone_id.choices).get(form.zone_id.data) }}</td>
    </tr>
  </table>
</div>
{% endblock %}